### ISSUE TITLE
BTTV problem

### ISSUE THREAD

**Issue by calophi** [RealityRipple/EmoteWall#3]
H there!  I love that you created this alternative to using Stream Elements, because aside from their bad politics it was annoying that it was going down all the time and I was constantly having to reconnect to the service. 

I only have one problem. The event kappagens are using my BTTV emotes first instead of my Twitch emotes. Is there a way to either switch the order that emotes are chosen or disable BTTV only for events but still allow them for a command kappagen? Thanks!

**Comment by RealityRipple** [comment]
I'm not sure what you mean by "first" - 

---

The priority order for emotes with identical names are:
1. Direct URL
2. Bit Cheers
3. User-specific emotes (usually from third-party subscriptions)
4. First-Party (Twitch/YT/Kick) Channel Emotes
5. Third-Party Channel Emotes
6. First-Party Global Emotes
7. Third-Party Global Emotes
8. Emojis

Meaning that if you have a Twitch Channel emote with the same name as an FFZ, BTTV, or 7TV emote, the Twitch one will be the one that's used.

---

If you mean the randomly selected emotes that occur with a kappagen command or event, there is no order - it's literally just a 100% random selection of all your Channel emotes, both first and third party.
For advanced control over exactly which emotes are used for which events, the Wizard has an "Emotes" list for each event and kappagen animation style in the advanced settings, which lets you enter any emote names, Emojis, or even direct URLs,, separated by spaces, which will be used as the pool to randomly choose from instead.

**Comment by calophi** [comment]
Hi, what I mean is that ALL of my emotes that show for events are from third party and none of my twitch ones show up at all. I guess I need to just configure set emotes to use. Thanks!

**Comment by calophi** [comment]
Ok, I looked but I don't see a way to have ONLY my twitch emotes pop up for an event in the wizard, I'm only seeing the animation style. I want folk to be able to use BTTV to do their own kappas, but I don't want any of those in my event kappas. I'm going to have to turn off all the event kappas because it's just annoying me at this point.

**Comment by RealityRipple** [comment]
This sounds like the symptoms of a bug that was resolved two months ago. If you are using the HTML file, a simple update might fix your issue.

You can control the advanced settings for any kappa animation style (or all enabled styles at once) using the advanced buttons: https://omnimg.realityripple.com/vw5CYn.gif

Choosing which emotes you want to use for an event is done with a list, as I said: https://omnimg.realityripple.com/RepLiZ.gif
